// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9DP9F-Z67CbIV4DQG9bpMxeyv125dNYU',
    appId: '1:780178259406:web:2c23abb50692740b6eff9f',
    messagingSenderId: '780178259406',
    projectId: 'madreq-ee4b7',
    authDomain: 'madreq-ee4b7.firebaseapp.com',
    storageBucket: 'madreq-ee4b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHwBaRtb54JdcPwoeY9v9sQVK1MeH46L0',
    appId: '1:780178259406:android:28bb67cd35799bac6eff9f',
    messagingSenderId: '780178259406',
    projectId: 'madreq-ee4b7',
    storageBucket: 'madreq-ee4b7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9DP9F-Z67CbIV4DQG9bpMxeyv125dNYU',
    appId: '1:780178259406:web:679cd70ae8719eee6eff9f',
    messagingSenderId: '780178259406',
    projectId: 'madreq-ee4b7',
    authDomain: 'madreq-ee4b7.firebaseapp.com',
    storageBucket: 'madreq-ee4b7.firebasestorage.app',
  );
}
